package com.rdktechnologies.likeeDatingApp.constant

object Constants {
    const val LOCAL_IMAGE_BASE_URL="http://localhost:8080/api/v1/file/"
    const val PRODUCTION_IMAGE_BASE_URL="http://ec2-65-1-154-130.ap-south-1.compute.amazonaws.com/api/v1/file/"
    const val FILE_NOT_FOUND = "File not found"
    const val ACCOUNT_IS_CREATED = "Account has been successfully registered"
    const val PRODUCT_IS_CREATED = "Product successfully created"
    const val PRODUCT_IS_UPDATED = "Product successfully updated"
    const val PRODUCT_IS_DELETED = "Product successfully deleted"
    const val DRIVER_IS_DELETED = "Driver successfully deleted"
    const val DRIVER_IS_UPDATED = "Driver successfully updated"
    const val DRIVER_IS_CREATED = "Driver successfully created"
    const val DRIVING_LICENCE_IS_ALREADY_REGISTERED = "Driving licence number already registered."
    const val CONTACT_NUMBER_IS_ALREADY_REGISTERED = "Contact number already registered."

    const val OWNER_IS_CREATED = "Owner successfully created"
    const val OWNER_IS_UPDATED = "Owner successfully updated"
    const val OWNER_IS_DELETED = "Owner successfully deleted"
    const val PRODUCT_NOT_FOUND = "Product not found"
    const val DRIVER_NOT_FOUND = "Driver not found"
    const val OWNER_NOT_FOUND = "Owner not found"
    const val VEHICLE_NOT_FOUND = "Vehicle not found"
    const val ROLE_IS_EMPTY_OR_INCORRECT = "Role is incorrect or empty"
    const val EMAIL_IS_ALREADY_REGISTERED = "Email is already registered"
    const val PHONE_NUMBER_IS_ALREADY_REGISTERED = "Phone Number is already registered"
    const val LOGIN_SUCCESSFULLY = "Logged in successfully"
    const val TRIP_CREATED_SUCCESSFULLY = "Trip created successfully"
    const val TRIP_UPDATED_SUCCESSFULLY = "Trip Updated successfully"
    const val TRIP_NOT_FOUND = "Trip not found"
    const val AGENCY_NOT_FOUND = "Agency not found"
    const val EMAIL_IS_SENT_TO_YOUR_REGISTERED_EMAIL_ADDRESS = "An email has been sent to your registered email address"
    const val FORGOT_PASSWORD_TIME_HAS_EXPIRED = "Forgot password OTP has expired"
    const val USERNAME_OR_PASSWORD_IS_INCORRECT = "Email or password is incorrect"
    const val USER_NOT_FOUND = "User not found"
    const val NEW_ACCESS_TOKEN_IS_CREATED = "New access token has been created"
    const val PROJECT_CREATED_SUCCESSFULLY = "Project created successfully"
    const val UNAUTHORIZED_ACCESS = "Unauthorized access"
    const val PROJECT_NOT_FOUND = "Project not found"
    const val MEDIA_NOT_FOUND = "Media not found"
    const val DOCUMENT_NOT_FOUND = "Document not found"
    const val DATA_FETCH_SUCCESSFULLY = "Data fetched successfully"
    const val PROJECT_DESCRIPTION_IS_UPDATED_SUCCESSFULLY = "Project description has been updated successfully"
    const val PROJECT_RESTORATION_DONE_SUCCESSFULLY = "Project restoration done successfully"
    const val USER_DELETED_SUCCESSFULLY = "User has been deleted successfully"
    const val CHECKLIST_SUCCESSFULLY_ADDED = "Checklist successfully added"
    const val CHECKLIST_SUCCESSFULLY_REMOVED = "Checklist successfully removed"
    const val CHECKLIST_SUCCESSFULLY_UPDATED = "Checklist successfully updated"
    const val CHECKLIST_NOT_FOUND = "Checklist not found"
    const val USER_IS_ALREADY_ASSIGNED_TO_THIS_PROJECT = "User is already assigned to this project"
    const val USER_IS_SUCCESSFULLY_ASSIGNED_PROJECT = "Project has been successfully assigned to the user"
    const val USER_IS_SUCCESSFULLY_REMOVED_FROM_PROJECT = "User has been successfully removed from the project"
    const val SOMETHING_WENT_WRONG = "Something went wrong"
    const val ENABLE_USER_BEFORE_CHANGING_PASSWORD = "Enable the user before changing the password"

    const val PASSWORD_HAS_BEEN_SUCCESSFULLY_CHANGED = "Password has been successfully changed"
    const val COMPANY_NAME = "Harris Water Main & Sewer"
    const val USER_DEACTIVATED_SUCCESSFULLY = "User deactivated successfully"
    const val USER_ACTIVATED_SUCCESSFULLY = "User activated successfully"
    const val PROJECT_IS_SUCCESSFULLY_DELETED = "Project has been successfully deleted"
    const val PASSWORD_NOT_VALID_TRY_DIFFERENT_PASSWORD = "Old password is not valid"
    const val LOGOUT_SUCCESSFULLY = "Logout Successfully"
    const val YOU_ARE_NOT_ALLOWED_TO_CREATE_PROJECT = "You are not allowed to create project"
    const val FILE_IS_UPLOADED_SUCCESSFULLY = "File is uploaded successfully"
    const val INVENTORY_NOT_FOUND = "Inventory not found"
    const val INVENTORY_IS_ASSIGN_SUCCESSFULLY = "Inventory has been assign successfully"
    const val INVENTORY_IS_REMOVED_SUCCESSFULLY = "Inventory has been removed successfully"
    const val INVENTORY_HAS_BEEN_CREATED_SUCCESSFULLY = "Inventory has been created successfully"
    const val MEDIA_HAS_BEEN_ADDED_SUCCESSFULLY = "Media has been added successfully"
    const val MEDIA_HAS_BEEN_DELETED_SUCCESSFULLY = "Media has been deleted successfully"
    const val DOCUMENT_DELETED_SUCCESSFULLY = "Document deleted successfully"
    const val MEDIA_TYPE_IS_INVALID = "Media type is invalid"
    const val DOCUMENT_TYPE_IS_INVALID = "Document type is invalid"

    const val TASK_IS_MARK_AS_COMPLETED = "Task has been mark as completed"
    const val TASK_IS_MARK_AS_NOT_COMPLETED = "Task has been mark as uncompleted"
    const val FIRST_NAME_IS_MANDATORY = "First name is mandatory"
    const val LAST_NAME_IS_MANDATORY = "Last name is mandatory"
    const val PHONE_NO_IS_MANDATORY = "Phone number is mandatory"
    const val PROFILE_IS_MANDATORY = "Profile is mandatory"
    const val PROFILE_HAS_BEEN_UPDATED_SUCCESSFULLY= "Profile has been updated successfully"
    const val NOTIFICATION_STATUS_IS_MANDATORY= "Notification status is mandatory"
    const val NOTIFICATION_STATUS_HAS_BEEN_CHANGED= "Notification status has been changed"

}
